export const data = [
  {
    id: 1,
    img: "/images/flag-brazil.png",
    title: "Germany",
    population: "81,770,900",
    region: "Europe",
    capital: "Berlin",
  },
  {
    id: 2,
    img: "/images/Germany.png",
    title: "Iceland",
    population: " 323,947",
    region: "Americas",
    capital: "Reykjavík",
  },
  {
    id: 3,
    img: "/images/flag-germany (1).jpg",
    title: "Brazil",
    population: "206,135,893",
    region: "Americas",
    capital: "Brasília",
  },
  {
    id: 4,
    img: "/images/Germany.png",
    title: "Iceland",
    population: " 323,947",
    region: "Americas",
    capital: "Reykjavík",
  },
  {
    id: 5,
    img: "/images/flag-germany (1).jpg",
    title: "Brazil",
    population: "206,135,893",
    region: "Americas",
    capital: "Brasília",
  },
  {
    id: 6,
    img: "/images/flag-brazil.png",
    title: "Germany",
    population: "81,770,900",
    region: "Europe",
    capital: "Berlin",
  },

  {
    id: 7,
    img: "/images/Germany.png",
    title: "Iceland",
    population: " 323,947",
    region: "Americas",
    capital: "Reykjavík",
  },
  {
    id: 8,
    img: "/images/flag-germany (1).jpg",
    title: "Brazil",
    population: "206,135,893",
    region: "Americas",
    capital: "Brasília",
  },
];
